@startuml
abstract class Vehiculo {
+Vehiculo(Ubicacion)
+atravesar(Obstaculo) : Efecto {abstract}
+atravesar(Sorpresa) : Efecto {abstract}
+atravesar(Meta) : Efecto
+mover(Direccion) : Casillero
+moverSentidoOpuesto();
}

class Auto{
+atravesar(Obstaculo) : Efecto {abstract}
+atravesar(Sorpresa) : Efecto {abstract}
}
class Moto{
+atravesar(Obstaculo) : Efecto {abstract}
+atravesar(Sorpresa) : Efecto {abstract}
}
class Camioneta{
+atravesar(Obstaculo) : Efecto {abstract}
+atravesar(Sorpresa) : Efecto {abstract}
}
Vehiculo <|-- Auto
Vehiculo <|-- Moto
Vehiculo <|-- Camioneta


@enduml
