@startuml

GPS -> Escenario

Calle ---> "0..1" Sorpresa
Calle --> Vehiculo
Calle -> Obstaculos

Escenario -> Vehiculo
Escenario -> Manzana

Manzana --> "1..*" Calle

Sorpresa --> Favorable
Sorpresa --> Desfavorable
Sorpresa --> CambioDeVehiculo

Vehiculo <|-- Moto
Vehiculo <|-- Camioneta
Vehiculo <|-- Coche

interface Obstaculos

Obstaculos <... Pozo
Obstaculos <... Policia
Obstaculos <... Piquete

@enduml