@startuml
title Se juega con un jugador se mueve a la derecha y hay un cambioVehiculo y Piquete
Actor actor
create "ubicacionVehiculo:Ubicacion"
actor -> "ubicacionVehiculo:Ubicacion": new Ubicacion(fila,columna)
create "auto:Auto"
actor -> "auto:Auto":<<new>>
create Juego
actor -> Juego: <<resetInstance(jugadores)>>
actor -> Juego:getInstance()
activate Juego
return Juego
create "direccion:DireccionDerecha"
actor -> "direccion:DireccionDerecha":<<new>>
actor -> Juego: moverVehiculo(direccion)
activate Juego
Juego -> "jugadorActivo:Jugador":moverVehiculo(direccion)
activate "jugadorActivo:Jugador"
"jugadorActivo:Jugador" -> "auto:Auto":             mover(direccion)
"jugadorActivo:Jugador" -> "auto:Auto":             mover(direccion)
activate "auto:Auto"

"auto:Auto" -> "direccion:DireccionDerecha":mover(ubicacionVehiculo)
activate "direccion:DireccionDerecha"
"direccion:DireccionDerecha" -> "ubicacionVehiculo:Ubicacion":mover(direccion)
activate "ubicacionVehiculo:Ubicacion"
deactivate "ubicacionVehiculo:Ubicacion"
deactivate "direccion:DireccionDerecha"

"auto:Auto" -> Escenario:getInstance()
activate Escenario
Escenario --> "auto:Auto":Escenario
deactivate Escenario
"auto:Auto" -> Escenario: buscarCasillero(ubicacionVehiculo)
activate Escenario
Escenario --> "auto:Auto":nuevoCasillero
deactivate Escenario

"auto:Auto" -> "direccion:DireccionDerecha":mover(ubicacionVehiculo)
activate "direccion:DireccionDerecha"
"direccion:DireccionDerecha" -> "ubicacionVehiculo:Ubicacion":mover(direccion)
activate "ubicacionVehiculo:Ubicacion"
deactivate "ubicacionVehiculo:Ubicacion"
deactivate "direccion:DireccionDerecha"
"auto:Auto" --> "jugadorActivo:Jugador": nuevoCasillero
deactivate "auto:Auto"
"jugadorActivo:Jugador" -> "nuevoCasillero:Casillero":atravezar(jugadorActivo)
activate "nuevoCasillero:Casillero"
"nuevoCasillero:Casillero" -> "jugadorActivo:Jugador": atravezar(cambioVehiculo)
deactivate "nuevoCasillero:Casillero"
"jugadorActivo:Jugador" -> "auto:Auto":atravezar(cambioVehiculo)
"auto:Auto" -> "Sorpresa":atravezar(auto)
create "efecto:EfectoGeneral"
"Sorpresa" -> "efecto:EfectoGeneral":<<new>>
create "efecto:EfectoMoverAlReves"
"Sorpresa" -> "efecto:EfectoMoverAlReves":<<new




@enduml
