@startuml UnAutoAtraviesaLaCiudadYSeEncuentraConUnPozo

actor ":Usuario"
create ":GPS"
":Usuario" --> ":GPS" : GPS(nombre, auto, filas, columnas)

create ":Jugador"
":GPS" --> ":Jugador" : Jugador(nombre, vehiculo)

create ":Escenario"
":GPS" --> ":Escenario" : Escenario(filas, columnas)

loop hasta completar el escenario
create ":EntreCalle"
":Escenario" --> ":EntreCalle" : new

create ":Calle"
":EntreCalle" --> ":Calle" : new
end

loop hasta toparse con un pozo
":Usuario" -> ":GPS" : mover(Direccion)
":GPS" -> ":Jugador" : moverVehiculo(Direccion)

":Jugador" -> "auto:Auto" : mover(Direccion)

"auto:Auto" -> ":EntreCalle" : mover(auto, Direccion)
":EntreCalle" -> ":Calle" : atravesarCalle(auto, Jugador)
end

":Calle" -> "pozo:Pozo" : pasarObstaculo(auto, Jugador)
"pozo:Pozo" -> ":Jugador" : incrementarMovimientos(3)

":GPS" -> ":Jugador" : puntaje()
":Jugador" -->> ":GPS" : puntaje

":GPS" -->> ":Usuario" : puntaje

@enduml